### ISSUE TITLE
Viewing logs in terminal

### ISSUE THREAD

**Issue by aspdev91** [codesbiome/electron-react-webpack-typescript-2021#11]
Is there any way to view the console logs from the main process? I used npm start and tried two approaches (1) appending "--enable-logging" to the front of "electron-forge start" and (2) setting the env variable ELECTRON_ENABLE_LOGGING=1

**Comment by codesbiome** [comment]
Hello @aspdev91, 

Console logs from the main process are visible in terminal by default.
Are you using some other `npm package` to do the console logging? Because `console.log()` method is showing logs in the terminal just fine :

![image](https://user-images.githubusercontent.com/46080054/118381497-10ef2100-b609-11eb-8b86-b69c53d52303.png)

**Comment by aspdev91** [comment]
Thanks @codesbiome I realized it was a package I installed that interfered with the logging
