### ISSUE TITLE
Support for target: "electron"

### ISSUE THREAD

**Issue by iieo** [codesbiome/electron-react-webpack-typescript-2021#24]
Would be cool to have the option to set the target in the webpack config to electron/electron-renderer

**Comment by codesbiome** [comment]
Hello @iieo 

The webpack `target` can be configured in webpack renderer config file.
To use the `electorn-renderer` target, following changes you can try: 

Set Target Property for Webpack Renderer Config :

```js
// tools/webpack/webpack.renderer.js

// .....
module.exports = {
  target: 'electron-renderer',
  module: {
    rules,
  },
  //.....
```

Enable `nodeIntegration` and Disable `contextIsolation` for Main window's `webPreferences` :
These options are enabled by default for this project for [security reasons](https://www.electronjs.org/docs/latest/tutorial/security#isolation-for-untrusted-content)
```ts
// src/main.ts

//.....
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
      //.....
    },
```

<br>

Just make sure to use the `minimal` branch of this project when trying other webpack targets, because the `master` branch requires `contextIsolation` for main [Electron Window](https://github.com/guasam/electron-window) context bridge. Disabling `contextIsolation` will cause errors during execution of program with master branch.

**Comment by iieo** [comment]
Thanks!
